kind: WorkspaceRegistry
apiVersion: v1beta1
metadata:
  name: kasm-cabeza-registry
spec:
  description: "Registro personalizado para mis workspaces"
  workspaces:
    - name: "Firefox Flash ESR"
      description: "Firefox ESR con Flash habilitado"
      path: "workspaces/firefox-flash-esr/workspace.yaml"
